### PR TITLE
Dannon diff preview

### PR DESCRIPTION
**Pull request by almahmoud**

### CODE REVIEW

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=\"alex@test.org\""

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=\"alex@test.org\""

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" does not exist. Installing it now. NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 18:19:56 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=\"alex@test.org\""

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=\"alex@test.org\""

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 18:34:45 2020 NAMESPACE: default STATUS: deployed REVISION: 2 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args='--set image.tag=latest --set configs."galaxy\\.yml".galaxy.single_user="alex@test.org"'

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" does not exist. Installing it now. NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:18:01 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:35:34 2020 NAMESPACE: default STATUS: deployed REVISION: 2 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs."galaxy\.yml".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:37:48 2020 NAMESPACE: default STATUS: deployed REVISION: 3 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:41:08 2020 NAMESPACE: default STATUS: deployed REVISION: 4 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:41:36 2020 NAMESPACE: default STATUS: deployed REVISION: 5 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:53:29 2020 NAMESPACE: default STATUS: deployed REVISION: 6 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 20:58:58 2020 NAMESPACE: default STATUS: deployed REVISION: 7 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 21:32:57 2020 NAMESPACE: default STATUS: deployed REVISION: 8 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.\"galaxy\\.yml\".galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
"Preview deleted"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" does not exist. Installing it now. NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 21:35:16 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.galaxy\.yml.galaxy.single_user=alex@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.galaxy\\.yml.galaxy.single_user=alex@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 22:43:33 2020 NAMESPACE: default STATUS: deployed REVISION: 2 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" has been upgraded. Happy Helming! NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 22:44:14 2020 NAMESPACE: default STATUS: deployed REVISION: 3 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by galaxy-k8s** [comment]
"Preview deleted"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.galaxy\\.yml.galaxy.single_user=alex@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.galaxy\\.yml.galaxy.single_user=alex2@test.org"

**Comment by almahmoud** [comment]
/preview args="--set image.tag=latest --set configs.galaxy\\.yml.galaxy.single_user=alex2@test.org"

**Comment by galaxy-k8s** [comment]
Release "galaxy-preview-21" does not exist. Installing it now. NAME: galaxy-preview-21 LAST DEPLOYED: Wed Aug 19 23:38:06 2020 NAMESPACE: default STATUS: deployed REVISION: 1 NOTES: 1. Get the application URL by running these commands: https://ci-test.usegvl.org/issue-21/galaxy

**Comment by galaxy-k8s** [comment]
"Preview deleted"

**Pull request merged**
